# Generated by Django 6.0.7 on 2026-07-22 14:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='nom',
        ),
        migrations.AddField(
            model_name='contact',
            name='cree_le',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 7, 22, 13, 59, 42, 34106, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='entreprise',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='tel',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
